---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DatabaseName:
    Type: String
    Default: camara
Resources:
  Database:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: Database to hold camara data