name: Data Lake Bucket
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Bucket
        run: | 
          aws cloudformation deploy \
            --stack-name cloud-atlas-data-lake \
            --template-file template.yaml \
            --parameter-overrides file://parameters.json